-- The legacy frontend still uses these quoted tables. They were present in
-- the hosted project but were not represented in the original migration set,
-- which made a fresh local Supabase reset fail before RLS could be applied.
-- `if not exists` keeps this compatible with an existing hosted schema.
create table if not exists public."Users" (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_name text,
  email text,
  profile_picture text,
  created_by uuid not null references auth.users(id) on delete cascade,
  grade integer,
  school text,
  credits integer not null default 100,
  name text,
  class_level integer,
  unique (created_by)
);

create table if not exists public."Chapter_contents" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  grade text,
  subject text,
  board text,
  summary text,
  chapter text
);

create table if not exists public."Questions_Created" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  grade text,
  subject text,
  chapter text,
  difficulty_level text,
  length text,
  special_instructions text[] not null default '{}',
  test jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id) on delete cascade
);

create table if not exists public."AnswerSheetImages" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  image_url text[],
  uploaded_by uuid not null references auth.users(id) on delete cascade,
  for_test bigint,
  feedback bigint
);

create table if not exists public."FeedbackTest" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  given_by uuid not null references auth.users(id) on delete cascade,
  for_test bigint,
  feedback jsonb not null default '{}'::jsonb
);

create table if not exists public."Feedback_table_2" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  feedback_by uuid not null references auth.users(id) on delete cascade,
  name text,
  feedback text
);

create index if not exists users_created_by_idx on public."Users" (created_by);
create index if not exists questions_created_by_idx on public."Questions_Created" (created_by, created_at desc);
create index if not exists answer_sheet_images_uploaded_by_idx on public."AnswerSheetImages" (uploaded_by, created_at desc);
create index if not exists feedback_test_given_by_idx on public."FeedbackTest" (given_by, created_at desc);

alter table public."Users" enable row level security;
alter table public."Chapter_contents" enable row level security;
alter table public."Questions_Created" enable row level security;
alter table public."AnswerSheetImages" enable row level security;
alter table public."FeedbackTest" enable row level security;
alter table public."Feedback_table_2" enable row level security;

drop policy if exists "Users can insert their own profile" on public."Users";
drop policy if exists "Users can update their own profile" on public."Users";
drop policy if exists "Users can view their own profile" on public."Users";

create policy "Users can view their own profile"
on public."Users" for select to authenticated
using ((select auth.uid()) = created_by);

create policy "Users can insert their own profile"
on public."Users" for insert to authenticated
with check ((select auth.uid()) = created_by);

create policy "Users can update their own profile"
on public."Users" for update to authenticated
using ((select auth.uid()) = created_by)
with check ((select auth.uid()) = created_by);

drop policy if exists "Enable read access for all users" on public."Chapter_contents";
drop policy if exists "Authenticated users can read chapter contents" on public."Chapter_contents";

create policy "Authenticated users can read chapter contents"
on public."Chapter_contents" for select to authenticated
using (true);

drop policy if exists "Users can view their own tests" on public."Questions_Created";
drop policy if exists "Users can create their own tests" on public."Questions_Created";

create policy "Users can view their own tests"
on public."Questions_Created" for select to authenticated
using ((select auth.uid()) = created_by);

create policy "Users can create their own tests"
on public."Questions_Created" for insert to authenticated
with check ((select auth.uid()) = created_by);

drop policy if exists "Users can view their own answer sheet records" on public."AnswerSheetImages";
drop policy if exists "Users can create their own answer sheet records" on public."AnswerSheetImages";

create policy "Users can view their own answer sheet records"
on public."AnswerSheetImages" for select to authenticated
using ((select auth.uid()) = uploaded_by);

create policy "Users can create their own answer sheet records"
on public."AnswerSheetImages" for insert to authenticated
with check ((select auth.uid()) = uploaded_by);

drop policy if exists "Users can view their own feedback" on public."FeedbackTest";
drop policy if exists "Users can create their own feedback" on public."FeedbackTest";

create policy "Users can view their own feedback"
on public."FeedbackTest" for select to authenticated
using ((select auth.uid()) = given_by);

create policy "Users can create their own feedback"
on public."FeedbackTest" for insert to authenticated
with check ((select auth.uid()) = given_by);

drop policy if exists "Users can submit general feedback" on public."Feedback_table_2";

create policy "Users can submit general feedback"
on public."Feedback_table_2" for insert to authenticated
with check ((select auth.uid()) = feedback_by);

grant select, insert, update on table public."Users" to authenticated;
grant select on table public."Chapter_contents" to authenticated;
grant select, insert on table public."Questions_Created" to authenticated;
grant select, insert on table public."AnswerSheetImages" to authenticated;
grant select, insert on table public."FeedbackTest" to authenticated;
grant insert on table public."Feedback_table_2" to authenticated;

-- Trusted backend jobs use the service-role client. RLS is still bypassed by
-- that role, but Postgres privileges must also be explicit when new-table
-- auto-exposure is disabled in local and hosted Supabase projects.
grant select, insert, update, delete on table public."Users" to service_role;
grant select, insert, update, delete on table public."Chapter_contents" to service_role;
grant select, insert, update, delete on table public."Questions_Created" to service_role;
grant select, insert, update, delete on table public."AnswerSheetImages" to service_role;
grant select, insert, update, delete on table public."FeedbackTest" to service_role;
grant select, insert, update, delete on table public."Feedback_table_2" to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on table public."Users" from anon;
revoke all on table public."Chapter_contents" from anon;
revoke all on table public."Questions_Created" from anon;
revoke all on table public."AnswerSheetImages" from anon;
revoke all on table public."FeedbackTest" from anon;
revoke all on table public."Feedback_table_2" from anon;

drop policy if exists "full-access 1hkhm8h_0" on storage.objects;
drop policy if exists "full-access 1hkhm8h_1" on storage.objects;
drop policy if exists "full-access 1hkhm8h_2" on storage.objects;
drop policy if exists "full-access 1hkhm8h_3" on storage.objects;
drop policy if exists "full-policy-test b1ln73_0" on storage.objects;
drop policy if exists "full-policy-test b1ln73_1" on storage.objects;
drop policy if exists "full-policy-test b1ln73_2" on storage.objects;
drop policy if exists "full-policy-test b1ln73_3" on storage.objects;
drop policy if exists "Question papers authenticated uploads" on storage.objects;
drop policy if exists "Question papers authenticated updates" on storage.objects;
drop policy if exists "Question papers authenticated deletes" on storage.objects;
drop policy if exists "Answer sheets authenticated uploads" on storage.objects;
drop policy if exists "Answer sheets authenticated updates" on storage.objects;
drop policy if exists "Answer sheets authenticated deletes" on storage.objects;

create policy "Question papers authenticated uploads"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'question-papers-test'
  and (storage.foldername(name))[1] = (select auth.jwt()->>'sub')
);

create policy "Question papers authenticated updates"
on storage.objects for update to authenticated
using (
  bucket_id = 'question-papers-test'
  and (storage.foldername(name))[1] = (select auth.jwt()->>'sub')
)
with check (
  bucket_id = 'question-papers-test'
  and (storage.foldername(name))[1] = (select auth.jwt()->>'sub')
);

create policy "Question papers authenticated deletes"
on storage.objects for delete to authenticated
using (
  bucket_id = 'question-papers-test'
  and (storage.foldername(name))[1] = (select auth.jwt()->>'sub')
);

create policy "Answer sheets authenticated uploads"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'answer-sheet-test'
  and (storage.foldername(name))[1] = (select auth.jwt()->>'sub')
);

create policy "Answer sheets authenticated updates"
on storage.objects for update to authenticated
using (
  bucket_id = 'answer-sheet-test'
  and (storage.foldername(name))[1] = (select auth.jwt()->>'sub')
)
with check (
  bucket_id = 'answer-sheet-test'
  and (storage.foldername(name))[1] = (select auth.jwt()->>'sub')
);

create policy "Answer sheets authenticated deletes"
on storage.objects for delete to authenticated
using (
  bucket_id = 'answer-sheet-test'
  and (storage.foldername(name))[1] = (select auth.jwt()->>'sub')
);
